const STAGES = Object.freeze({
    PROBLEM_UNDERSTANDING: "PROBLEM_UNDERSTANDING",
    APPROACH_DISCUSSION: "APPROACH_DISCUSSION",
    CODING: "CODING",
    CODE_REVIEW: "CODE_REVIEW",
    FINAL_REPORT: "FINAL_REPORT"
});

module.exports = STAGES;